export const ServiceTokens = {
  Config: 'Config',
  Logger: 'Logger',
  ErpReadPort: 'ErpReadPort',
  VoucherParser: 'VoucherParser',
  VoucherMapper: 'VoucherMapper',
  TallyVoucherExtractor: 'TallyVoucherExtractor',
  VoucherReadPort: 'VoucherReadPort',
  VoucherExtraction: 'VoucherExtraction',
  VoucherSynchronization: 'VoucherSynchronization',
  VoucherApplication: 'VoucherApplication',
  VoucherSync: 'VoucherSync',
  TallyConnection: 'TallyConnection',
  SyncEngine: 'SyncEngine',
  XmlImport: 'XmlImport',
  CompanyDiscovery: 'CompanyDiscovery',
  CompanyResolver: 'CompanyResolver',
  ConnectorSession: 'ConnectorSession',
  MasterData: 'MasterData',
  LedgerSync: 'LedgerSync',
  StockItemSync: 'StockItemSync',
  VoucherFoundation: 'VoucherFoundation',
  TallyDiagnostics: 'TallyDiagnostics',
  LocalDatabase: 'LocalDatabase',
  ApiServer: 'ApiServer',
  Licensing: 'Licensing',
  Scheduler: 'Scheduler',
  HealthService: 'HealthService',
} as const;

export type ServiceToken = (typeof ServiceTokens)[keyof typeof ServiceTokens];
