name: venture
repository: https://github.com/jajusri/venture

packages:
  - apps/venture_mobile
  - shared/packages/venture_core
  - shared/packages/venture_contracts

command:
  bootstrap:
    usePubspecOverrides: true
