export const lifecycleStatusFixture = {
  state: 'connected' as const,
  stateLabel: 'Connected' as const,
  managedByDesktop: false,
  externalProcessDetected: true,
  lastSuccessfulHealthCheck: '2026-07-23T00:00:00.000Z',
  lastError: null,
  restartAttempts: 0,
  processExitCode: null,
  connectorExecutable: process.execPath,
  connectorPort: 8080,
  userMessage: null,
  managedProcessPid: null,
};

export const settingsFixture = {
  connectorUrl: 'http://localhost:8080',
  connectorHost: '127.0.0.1',
  apiVersion: '1.0.0',
  desktopVersion: '0.4.3',
  erpType: 'tally',
  pollIntervalSeconds: 5,
  connectorExecutable: process.execPath,
  connectorPort: 8080,
  autoStartConnector: true,
  healthPollIntervalMs: 5000,
  startupTimeoutMs: 30000,
  shutdownGraceMs: 5000,
  maxRestartAttempts: 5,
  reconnectBaseDelayMs: 1000,
  logLevel: 'info',
  diagnosticsRetentionDays: 14,
  tallyHost: 'localhost',
  tallyPort: 9000,
  configSource: 'persisted/default',
  configStatus: 'loaded',
  restartRequired: false,
};

export const diagnosticsFixture = {
  generatedAt: '2026-07-23T00:00:00.000Z',
  desktopVersion: '0.4.3',
  connectorVersion: '0.3.1',
  electronVersion: '33.0.0',
  nodeVersion: process.versions.node,
  platform: process.platform,
  osRelease: 'test',
  architecture: process.arch,
  uptimeSeconds: 10,
  connectorBaseUrl: 'http://localhost:8080',
  connectorProcessState: 'Connected',
  connectorOwnership: 'desktop-managed' as const,
  connectorPid: 1234,
  healthStatus: 'ok',
  healthReachable: true,
  lastSuccessfulHealthCheck: '2026-07-23T00:00:00.000Z',
  tallyReachable: true,
  connectorBindHost: '127.0.0.1',
  connectorNetworkExposure: 'loopback' as const,
  connectorNetworkExposureWarning: null,
  sessionStatus: 'ACTIVE' as const,
  selectedCompanyPresent: true,
  sessionDisplayLabel: 'ACTIVE · company selected',
  configSource: 'persisted/default',
  configStatus: 'loaded',
  logFile: { category: 'desktop-log' as const, basename: 'budcom-desktop.log', available: true },
  fileLoggingAvailable: true,
  recentLifecycleEvents: [],
  recentErrors: [],
};
