package com.jajusri.venture.feature.party.sharing

import android.net.Uri
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Generates and saves one Tally-enrichment XML export file (MVP-1.1-D). Deliberately narrower
 * than [com.jajusri.venture.feature.masterdata.ledger.sharing.LedgerStatementShareCoordinator]:
 * only Save-via-SAF is supported (no share-intent/WhatsApp path) — an enrichment XML is meant for
 * manual import into Tally, not for sending to a third party.
 */
interface PartyXmlExportCoordinator {
    /** Writes [xmlContent] (already fully generated by [com.jajusri.venture.feature.party.domain.xml.TallyLedgerXmlGenerator])
     * to a managed cache file. Does not touch Tally or the Connector. */
    suspend fun prepareXml(xmlContent: String, suggestedFilename: String): PartyXmlExportResult<PreparedPartyXmlExport>
    suspend fun saveXml(export: PreparedPartyXmlExport, destination: Uri): PartyXmlExportResult<Unit>
    fun releaseXml(export: PreparedPartyXmlExport)
}

data class PreparedPartyXmlExport(
    val cacheFilePath: String,
    val suggestedFilename: String,
)

sealed interface PartyXmlExportResult<out T> {
    data class Success<T>(val value: T) : PartyXmlExportResult<T>
    data class Failure(val message: String) : PartyXmlExportResult<Nothing>
}

/** `ledgerName` only — never includes field values, since a filename is more likely to be
 * glanced at (recent-files lists, screenshots) than the file's own content. */
fun sanitizedPartyXmlExportFilename(ledgerName: String, nowEpochMillis: Long): String {
    val safe = ledgerName
        .trim()
        .replace(Regex("[^A-Za-z0-9._-]+"), "-")
        .trim('.', '-', '_')
        .take(60)
        .ifBlank { "party" }
    val stamp = SimpleDateFormat("yyyyMMdd-HHmmss", Locale.US).format(Date(nowEpochMillis))
    return "VENTURE-Tally-Export-$safe-$stamp.xml"
}
