package com.budcom.android.feature.party.data.local

import androidx.room.Entity
import androidx.room.Index

/**
 * Stable BUDCOM Universal Party Identity — never a Tally Ledger itself, see [PartySourceLinkEntity].
 * Company-scoped exactly like [com.budcom.android.feature.masterdata.ledger.data.local.LedgerEntity]
 * (plain `companyId` column, composite primary key, no Room `ForeignKey`).
 */
@Entity(
    tableName = "cached_parties",
    primaryKeys = ["companyId", "partyId"],
    indices = [
        Index(value = ["companyId"]),
        Index(value = ["companyId", "displayName"]),
        Index(value = ["companyId", "classification"]),
        Index(value = ["companyId", "primaryPhoneNormalized"]),
    ],
)
data class PartyEntity(
    val companyId: String,
    val partyId: String,
    val displayName: String,
    val classification: String,
    val primaryPhone: String?,
    val primaryPhoneNormalized: String?,
    val primaryEmail: String?,
    val addressLine1: String?,
    val addressCity: String?,
    val addressState: String?,
    val addressPincode: String?,
    val gstin: String?,
    val createdAt: Long,
    val updatedAt: Long,
)

/**
 * Links a [PartyEntity] to an external accounting entity — for MVP-1.1-A always a Tally Ledger.
 * The primary key is the natural external key `(companyId, sourceType, externalEntityId)`, not
 * an autogenerated id: this is what makes "the same ledger GUID within the same company always
 * maps to the same Party" a simple upsert-by-natural-key operation (mirroring how
 * `cached_ledgers`/`cached_vouchers` use their own remote id as part of the primary key) rather
 * than a separately-enforced uniqueness rule.
 */
@Entity(
    tableName = "party_source_links",
    primaryKeys = ["companyId", "sourceType", "externalEntityId"],
    indices = [
        Index(value = ["companyId", "partyId"]),
    ],
)
data class PartySourceLinkEntity(
    val companyId: String,
    val sourceType: String,
    val externalEntityId: String,
    val partyId: String,
    val sourceInstanceId: String,
    val externalDisplayName: String,
    val identitySource: String,
    val lastConfirmedAt: Long,
)

/**
 * Field-level confirmation/provenance tracking (architecture §5/§6) for the Tally-compatible
 * enrichable fields on [PartyEntity] (see `PartyFieldNames`). Deliberately normalized into its
 * own table, keyed by `(companyId, partyId, fieldName)`, rather than one provenance column per
 * field on [PartyEntity] — adding a new trackable field later needs no schema migration.
 */
@Entity(
    tableName = "party_field_provenance",
    primaryKeys = ["companyId", "partyId", "fieldName"],
    indices = [Index(value = ["companyId", "partyId"])],
)
data class PartyFieldProvenanceEntity(
    val companyId: String,
    val partyId: String,
    val fieldName: String,
    val state: String,
    val tallyValue: String?,
    val budcomValue: String?,
    val lastConfirmedAt: Long?,
    val lastExportedAt: Long?,
    val updatedAt: Long,
)

/**
 * One person under a Party (Owner/Purchase/Accounts/Office/...). Provenance here is a single
 * whole-record confirmation state (not per-field like [PartyFieldProvenanceEntity]) since only
 * the Tally-compatible primary contact-person fields participate in XML export as one unit.
 */
@Entity(
    tableName = "party_contact_persons",
    primaryKeys = ["companyId", "contactPersonId"],
    indices = [Index(value = ["companyId", "partyId"])],
)
data class PartyContactPersonEntity(
    val companyId: String,
    val contactPersonId: String,
    val partyId: String,
    val name: String,
    val designation: String?,
    val mobile: String?,
    val mobileNormalized: String?,
    val whatsappNumber: String?,
    val email: String?,
    val isPrimary: Boolean,
    val provenance: String,
    val createdAt: Long,
    val updatedAt: Long,
)

/**
 * BUDCOM-only Party note (architecture §17/§17.1 — MVP-1.1-C). Never enters Tally XML. A note may
 * optionally reference a synced Voucher by its existing stable id — never duplicating Voucher
 * data locally, only the reference; the Voucher itself may later become locally unavailable
 * (e.g. outside the currently-synced window), which the read side must handle gracefully rather
 * than treating as an error.
 */
@Entity(
    tableName = "party_notes",
    primaryKeys = ["companyId", "noteId"],
    indices = [Index(value = ["companyId", "partyId", "createdAt"])],
)
data class PartyNoteEntity(
    val companyId: String,
    val noteId: String,
    val partyId: String,
    val body: String,
    val linkedVoucherId: String?,
    val createdAt: Long,
    val updatedAt: Long,
)

/**
 * Lightweight audit trail for one Tally-enrichment XML export (MVP-1.1-D, architecture §18). Never
 * stores raw field values — only field *names* and output-file metadata — so this table is safe to
 * read/export without itself becoming a sensitive-data surface.
 */
@Entity(
    tableName = "party_export_events",
    primaryKeys = ["companyId", "exportId"],
    indices = [Index(value = ["companyId", "partyId", "createdAt"])],
)
data class PartyExportEventEntity(
    val companyId: String,
    val exportId: String,
    val partyId: String,
    val createdAt: Long,
    val outputFileName: String,
    val fieldNamesCsv: String,
)
