package com.jajusri.venture.core.security

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.inject.Inject
import javax.inject.Singleton

/** Bumped only if the ciphertext/IV encoding itself changes shape (never for a key rotation). */
const val CREDENTIAL_CIPHER_FORMAT_VERSION = 1

private const val ANDROID_KEYSTORE_PROVIDER = "AndroidKeyStore"
private const val KEY_ALIAS = "venture_pairing_credential_key_v1"
private const val TRANSFORMATION = "AES/GCM/NoPadding"
private const val GCM_TAG_LENGTH_BITS = 128
private const val AES_KEY_SIZE_BITS = 256

/**
 * Production [CredentialCipher] — a single non-exportable AES-256-GCM key held in
 * `AndroidKeyStore` under one stable alias. No user-authentication requirement (MVP-1 needs
 * background sync to keep working without a biometric/PIN prompt). A fresh random 12-byte IV is
 * generated by the Keystore provider itself on every [encrypt] call (the standard behavior when
 * `Cipher.init(ENCRYPT_MODE, key)` is called without an explicit IV for a Keystore-backed GCM
 * key) — never reused, never caller-supplied.
 */
@Singleton
class AndroidKeystoreCredentialCipher @Inject constructor() : CredentialCipher {

    private val keyStore: KeyStore by lazy {
        KeyStore.getInstance(ANDROID_KEYSTORE_PROVIDER).apply { load(null) }
    }

    override fun hasKey(): Boolean = try {
        keyStore.containsAlias(KEY_ALIAS)
    } catch (e: Exception) {
        false
    }

    override fun encrypt(plaintext: ByteArray): CredentialEncryptionResult = try {
        val key = getOrCreateKey()
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, key)
        val ciphertext = cipher.doFinal(plaintext)
        CredentialEncryptionResult.Success(
            EncryptedPayload(ciphertext = ciphertext, iv = cipher.iv, formatVersion = CREDENTIAL_CIPHER_FORMAT_VERSION),
        )
    } catch (e: Exception) {
        CredentialEncryptionResult.KeystoreUnavailable
    }

    override fun decrypt(payload: EncryptedPayload): CredentialDecryptionResult {
        if (payload.formatVersion != CREDENTIAL_CIPHER_FORMAT_VERSION) {
            return CredentialDecryptionResult.InvalidCiphertext
        }
        val key = try {
            keyStore.getKey(KEY_ALIAS, null) as? SecretKey ?: return CredentialDecryptionResult.KeyMissing
        } catch (e: Exception) {
            return CredentialDecryptionResult.KeyMissing
        }
        return try {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(GCM_TAG_LENGTH_BITS, payload.iv))
            CredentialDecryptionResult.Success(cipher.doFinal(payload.ciphertext))
        } catch (e: Exception) {
            // Wrong key, tampered ciphertext, and corrupt/mismatched IV all surface here as an
            // AEADBadTagException/IllegalArgumentException/etc — all collapse to one explicit
            // "invalid" outcome rather than distinguishing tamper-vs-corruption to the caller.
            CredentialDecryptionResult.InvalidCiphertext
        }
    }

    /** Never silently regenerates over an existing key — only called when [hasKey] would be false. */
    private fun getOrCreateKey(): SecretKey {
        (keyStore.getKey(KEY_ALIAS, null) as? SecretKey)?.let { return it }
        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE_PROVIDER)
        val spec = KeyGenParameterSpec.Builder(KEY_ALIAS, KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT)
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(AES_KEY_SIZE_BITS)
            .setUserAuthenticationRequired(false)
            .build()
        generator.init(spec)
        return generator.generateKey()
    }
}
